# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClockWidget(object):
    def setupUi(self, ClockWidget):
        ClockWidget.setObjectName("ClockWidget")
        ClockWidget.resize(314, 69)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ClockWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ClockWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(ClockWidget)
        QtCore.QMetaObject.connectSlotsByName(ClockWidget)

    def retranslateUi(self, ClockWidget):
        _translate = QtCore.QCoreApplication.translate
        ClockWidget.setWindowTitle(_translate("ClockWidget", "Form"))
        self.label.setText(_translate("ClockWidget", "TextLabel"))
