# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CopyRight.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CopyRight(object):
    def setupUi(self, CopyRight):
        CopyRight.setObjectName("CopyRight")
        CopyRight.resize(476, 291)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CopyRight)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CopyRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(CopyRight)
        QtCore.QMetaObject.connectSlotsByName(CopyRight)

    def retranslateUi(self, CopyRight):
        _translate = QtCore.QCoreApplication.translate
        CopyRight.setWindowTitle(_translate("CopyRight", "CopyRight"))
        self.label.setText(_translate("CopyRight", "TimeArranger 作者：王潇  学号：20009100892"))
