# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogWidget(object):
    def setupUi(self, LogWidget):
        LogWidget.setObjectName("LogWidget")
        LogWidget.resize(383, 139)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.log_msg = QtWidgets.QLabel(LogWidget)
        self.log_msg.setObjectName("log_msg")
        self.verticalLayout.addWidget(self.log_msg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.log_level = QtWidgets.QLabel(LogWidget)
        self.log_level.setObjectName("log_level")
        self.horizontalLayout.addWidget(self.log_level)
        self.log_time = QtWidgets.QLabel(LogWidget)
        self.log_time.setObjectName("log_time")
        self.horizontalLayout.addWidget(self.log_time)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LogWidget)
        QtCore.QMetaObject.connectSlotsByName(LogWidget)

    def retranslateUi(self, LogWidget):
        _translate = QtCore.QCoreApplication.translate
        LogWidget.setWindowTitle(_translate("LogWidget", "Form"))
        self.log_msg.setText(_translate("LogWidget", "日志信息"))
        self.log_level.setText(_translate("LogWidget", "日志等级"))
        self.log_time.setText(_translate("LogWidget", "日志记录时间"))
