# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StatisticsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticsWidget(object):
    def setupUi(self, StatisticsWidget):
        StatisticsWidget.setObjectName("StatisticsWidget")
        StatisticsWidget.resize(946, 732)
        self.verticalLayout = QtWidgets.QVBoxLayout(StatisticsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_view_mode = QtWidgets.QComboBox(StatisticsWidget)
        self.comboBox_view_mode.setObjectName("comboBox_view_mode")
        self.comboBox_view_mode.addItem("")
        self.comboBox_view_mode.addItem("")
        self.comboBox_view_mode.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_view_mode)
        self.dateEdit_begin = QtWidgets.QDateEdit(StatisticsWidget)
        self.dateEdit_begin.setObjectName("dateEdit_begin")
        self.horizontalLayout.addWidget(self.dateEdit_begin)
        self.dateEdit_end = QtWidgets.QDateEdit(StatisticsWidget)
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.horizontalLayout.addWidget(self.dateEdit_end)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.GraphicLayout = QtWidgets.QHBoxLayout()
        self.GraphicLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.GraphicLayout.setContentsMargins(-1, 0, -1, -1)
        self.GraphicLayout.setObjectName("GraphicLayout")
        self.verticalLayout.addLayout(self.GraphicLayout)

        self.retranslateUi(StatisticsWidget)
        QtCore.QMetaObject.connectSlotsByName(StatisticsWidget)

    def retranslateUi(self, StatisticsWidget):
        _translate = QtCore.QCoreApplication.translate
        StatisticsWidget.setWindowTitle(_translate("StatisticsWidget", "历史使用统计"))
        self.comboBox_view_mode.setToolTip(_translate("StatisticsWidget", "选择视图方式(注：日视图最多显示7天的内容)"))
        self.comboBox_view_mode.setItemText(0, _translate("StatisticsWidget", "日视图"))
        self.comboBox_view_mode.setItemText(1, _translate("StatisticsWidget", "周视图"))
        self.comboBox_view_mode.setItemText(2, _translate("StatisticsWidget", "月视图"))
        self.dateEdit_begin.setToolTip(_translate("StatisticsWidget", "请选择开始日期"))
        self.dateEdit_end.setToolTip(_translate("StatisticsWidget", "请选择结束日期"))
