# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WebBlockDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WebBlockDialog(object):
    def setupUi(self, WebBlockDialog):
        WebBlockDialog.setObjectName("WebBlockDialog")
        WebBlockDialog.resize(648, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(WebBlockDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(WebBlockDialog)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.buttonBox = QtWidgets.QDialogButtonBox(WebBlockDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(WebBlockDialog)
        self.buttonBox.accepted.connect(WebBlockDialog.accept)
        self.buttonBox.rejected.connect(WebBlockDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(WebBlockDialog)

    def retranslateUi(self, WebBlockDialog):
        _translate = QtCore.QCoreApplication.translate
        WebBlockDialog.setWindowTitle(_translate("WebBlockDialog", "Dialog"))
        self.listView.setToolTip(_translate("WebBlockDialog", "域名屏蔽列表"))
